from typing import Any
from pydantic import AliasChoices, BaseModel, Field


class TestGenerateRequest(BaseModel):
    domain: str = Field(..., description="Interview domain or defense topic", example="Distributed Database Architecture")
    question_count: int = Field(2, description="Number of questions to generate (e.g., 2, 3, 5, or 10)", example=2)
    difficulty_level: str = Field("junior", description="Baseline difficulty tier: junior, Mid-Level, or Senior", example="junior")
    adaptive_mode: bool = Field(True, description="Enable adaptive difficulty progression", example=True)
    format: str = Field("Technical Deep Dive", description="Interview format profile", example="Technical Deep Dive")


class GeneratedQuestionSchema(BaseModel):
    question_id: int = Field(..., description="Unique question identifier within the generated interview", example=1)
    question_text: str = Field(..., description="Target question text generated by AI engine", example="How would you handle split-brain scenarios in a multi-region cluster?")
    difficulty: str = Field("Mid-Level", description="Question difficulty: Junior, Mid-Level, or Senior", example="Mid-Level")
    difficulty_level: str = Field("Mid-Level", description="Alias for question difficulty level", example="Mid-Level")
    evaluation_criteria: list[str] = Field(
        default_factory=list,
        validation_alias=AliasChoices("evaluation_criteria", "criteria"),
        description="Key checkpoint criteria required in a successful response",
        example=["Explains Raft consensus quorum", "Mentions network partition isolation"]
    )


class TestGenerateResponse(BaseModel):
    session_id: str = Field(..., description="Generated session UUID for live routing", example="test-session-9876")
    domain: str = Field(..., description="Domain of generated interview", example="Distributed Database Architecture")
    format: str = Field(..., description="Interview format", example="Technical Deep Dive")
    difficulty_level: str = Field("Mid-Level", description="Baseline difficulty tier", example="Mid-Level")
    adaptive_mode: bool = Field(True, description="Whether adaptive difficulty is enabled", example=True)
    questions: list[GeneratedQuestionSchema] = Field(..., description="Generated questions with evaluation rubrics")


class QuestionEvaluateRequest(BaseModel):
    session_id: str | None = Field(None, description="Optional live session ID to broadcast grade event over WebSocket", example="session-123")
    question_id: int = Field(..., description="ID of question being evaluated", example=1)
    question_text: str = Field(..., description="Text of question being answered", example="How do you handle lock contention?")
    evaluation_criteria: list[str] = Field(
        default_factory=list,
        validation_alias=AliasChoices("evaluation_criteria", "criteria"),
        description="Evaluation criteria or key checkpoint requirements for grading",
        example=["Mentions mutex lock granularity", "Discusses lock-free data structures"]
    )
    transcript: str = Field("", description="Spoken or written response transcript", example="I use lock-free atomic CAS operations and fine-grained mutex locks.")
    difficulty_level: str = Field("Mid-Level", description="Difficulty tier under which response is evaluated", example="Mid-Level")
    adaptive_mode: bool = Field(True, description="Whether adaptive progression is active", example=True)


class QuestionEvaluateResponse(BaseModel):
    question_id: int = Field(..., description="Evaluated question ID", example=1)
    transcript: str = Field(..., description="Candidate transcript evaluated", example="I use lock-free atomic CAS operations...")
    overall_score: int = Field(..., description="Overall score for the response (0-100)", example=88)
    score: int = Field(..., description="Score alias (0-100)", example=88)
    accuracy_rating: str = Field(..., description="Qualitative evaluation rating", example="Strong Technical Defense")
    strengths: list[str] = Field(..., description="Key strengths identified in the answer")
    weaknesses: list[str] = Field(..., description="Key areas for improvement")
    actionable_improvements: str = Field(..., description="Targeted coaching recommendation")
    ideal_response_summary: str = Field(..., description="Concise model answer summary")
    difficulty_evaluated: str = Field("Mid-Level", description="Difficulty tier evaluated", example="Mid-Level")
    next_recommended_difficulty: str = Field("Mid-Level", description="Recommended difficulty for next question", example="Senior")
    audio_base64: str | None = Field(None, description="AssemblyAI Voice Agent generated speech feedback in base64 WAV format")


class TestCumulativeReportRequest(BaseModel):
    domain: str = Field("", description="Interview domain name", example="Backend Architecture")
    format: str = Field("", description="Interview format", example="System Design")
    evaluations: list[dict[str, Any]] = Field(default_factory=list, description="List of completed question evaluation response objects")


class TestCumulativeReportResponse(BaseModel):
    domain: str = Field(..., description="Interview domain", example="Backend Architecture")
    format: str = Field(..., description="Interview format", example="System Design")
    overall_score: int = Field(..., description="Overall cumulative score across all questions", example=84)
    readiness_percentage: int = Field(..., description="Calculated candidate readiness percentage (0-100)", example=87)
    total_questions_answered: int = Field(..., description="Number of questions answered in session", example=3)
    cumulative_strengths: list[str] = Field(..., description="Deduplicated top cumulative strengths")
    persistent_weaknesses: list[str] = Field(..., description="Deduplicated persistent weaknesses to address")
    action_plan: str = Field(..., description="Targeted actionable training plan for candidate")


class AudioEvaluateRequest(BaseModel):
    session_id: str | None = Field(None, description="Optional session id to broadcast grade event", example="session-456")
    question_id: int = Field(1, description="Question ID", example=1)
    question_text: str = Field(..., description="Target question text", example="Explain database sharding.")
    evaluation_criteria: list[str] = Field(
        default_factory=list,
        validation_alias=AliasChoices("evaluation_criteria", "criteria"),
        description="Evaluation criteria list",
        example=["Explains hash sharding vs range sharding"]
    )
    audio_base64: str = Field(..., description="Base64 encoded audio string (webm/mp3/wav/m4a)")
    difficulty_level: str = Field("junior", description="Baseline difficulty level", example="junior")
    adaptive_mode: bool = Field(True, description="Adaptive mode enabled", example=True)


